In [31]:
import json
import os
import numpy as np
from scipy.signal import convolve2d

# Assuming your JSON file is named 'example.json' and is located in the 'data' folder
folder_path = r'ARC-AGI\\data\\training'
file_name = '00d62c1b.json'
file_path = os.path.join(folder_path, file_name)

# Check if the file exists
if os.path.exists(file_path):
    # Open the file and load JSON data
    with open(file_path, 'r') as file:
        data = json.load(file)
    # Now 'data' contains the JSON contents
    print(json.dumps(data, indent=4))  # Replace with your processing logic
else:
    print(f"The file '{file_name}' does not exist in the folder '{folder_path}'.")


{
    "train": [
        {
            "input": [
                [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                ],
                [
                    0,
                    0,
                    3,
                    0,
                    0,
                    0
                ],
                [
                    0,
                    3,
                    0,
                    3,
                    0,
                    0
                ],
                [
                    0,
                    0,
                    3,
                    0,
                    3,
                    0
                ],
                [
                    0,
                    0,
                    0,
                    3,
                    0,
                    0
                ],
                [
                    0,
                    0,
                

In [46]:
trainInput = list()
trainOutput = list()

for i in range(len(data['train'])):
    trainInput.append(np.array(data['train'][i]['input']))
    trainOutput.append(np.array(data['train'][i]['output']))
print(trainInput[0])
print(trainOutput[0])


orth_kernel = np.array([[0, 1, 0],
                        [1, 1, 1],
                        [0, 1, 0]])
surround_kernel = np.array([[1, 1, 1],
                            [1, 0, 1],
                            [1, 1, 1]])
vert_neighbors_kernel = np.array([[0, 1, 0],
                                  [0, 1, 0],
                                  [0, 1, 0]])
hor_neighbors_kernel = np.array([[0, 0, 0],
                                 [1, 0, 1],
                                 [0, 0, 0]])
vert_Edge_kernel =np.array([[-1, 0, 1],
                            [-1, 0, 1],
                            [-1, 0, 1]])
hor_Edge_kernel = np.array([[-1, -1, -1],
                            [0, 0, 0],
                            [1, 1, 1]])
sharp_kernel =    np.array([[0, -1, 0],
                            [-1, 5, -1],
                            [0, -1, 0]])

convolved_input = [convolve2d(matrix, vert_neighbors_kernel, mode='same', boundary='symm') for matrix in trainInput]
print(convolved_input[0])

[[0 0 0 0 0 0]
 [0 0 3 0 0 0]
 [0 3 0 3 0 0]
 [0 0 3 0 3 0]
 [0 0 0 3 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 3 0 0 0]
 [0 3 4 3 0 0]
 [0 0 3 4 3 0]
 [0 0 0 3 0 0]
 [0 0 0 0 0 0]]
[[0 0 3 0 0 0]
 [0 3 3 3 0 0]
 [0 3 6 3 3 0]
 [0 3 3 6 3 0]
 [0 0 3 3 3 0]
 [0 0 0 3 0 0]]
